name: aboutme
description: Show off!!.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_web_plugins:
    sdk: flutter
  stacked_themes: ^0.2.2+2
  lottie: ^0.7.0+1
  get_it:

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts: ^1.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/art1.jpg
    - kk.jpg

  
